apiVersion: 1

datasources:
  - name: PostgreSQL-Heartbeat
    type: postgres
    url: postgres:5432
    database: heartbeat_db
    user: heartbeat_user
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
    isDefault: true
    editable: true
